# Simplified schema for text-to-SQL task
# Based on the flight database

SCHEMA_DESCRIPTION = """Tables: flight(flight_id, from_airport, to_airport, departure_time, arrival_time, airline_code, flight_days, stops, aircraft_code_sequence), airport(airport_code, airport_name, airport_location, state_code, country_name, time_zone_code), airport_service(city_code, airport_code, miles_distant, direction, minutes_distant), city(city_code, city_name, state_code, country_name, time_zone_code), state(state_code, state_name, country_name), airline(airline_code, airline_name, note), flight_stop(flight_id, stop_number, stop_days, stop_airport, arrival_time, arrival_airline, arrival_flight_number, departure_time, departure_airline, departure_flight_number, stop_time), fare(fare_id, from_airport, to_airport, fare_basis_code, fare_airline, restriction_code, one_direction_cost, round_trip_cost, round_trip_required), flight_fare(flight_id, fare_id), fare_basis(fare_basis_code, booking_class, class_type, premium, economy, discounted, night, season, basis_days), days(days_code, day_name), date_day(month_number, day_number, year, day_name), equipment_sequence(aircraft_code_sequence, aircraft_code), aircraft(aircraft_code, aircraft_description, manufacturer, basic_type, engines, propulsion, wide_body, wing_span, length, weight, capacity, pay_load, cruising_speed, range_miles, pressurized), food_service(meal_code, meal_number, compartment, meal_description), ground_service(city_code, airport_code, transport_type, ground_fare), class_of_service(booking_class, rank, class_description), time_zone(time_zone_code, time_zone_name), time_interval(period, begin_time, end_time), dual_carrier(main_airline, low_flight_number, high_flight_number, dual_airline, service_name), compartment_class(compartment, class_type), month(month_number, month_name), restriction(restriction_code, advance_purchase, stopovers, saturday_stay_required, minimum_stay, maximum_stay, application, no_discounts)"""

COMPACT_SCHEMA = """flight(flight_id,from_airport,to_airport,departure_time,arrival_time,airline_code,flight_days,stops), airport_service(city_code,airport_code), city(city_code,city_name,state_code), state(state_code,state_name), airline(airline_code,airline_name), flight_stop(flight_id,stop_airport), fare(fare_id,from_airport,to_airport,fare_airline,one_direction_cost,round_trip_cost,round_trip_required), flight_fare(flight_id,fare_id), fare_basis(fare_basis_code,class_type), days(days_code,day_name), date_day(month_number,day_number,year,day_name), equipment_sequence(aircraft_code_sequence,aircraft_code), aircraft(aircraft_code,aircraft_description), food_service(meal_code,meal_description), airport(airport_code,airport_name)"""


def add_schema_to_query(nl_query, use_compact=True):
    """Add schema information to natural language query."""
    schema = COMPACT_SCHEMA if use_compact else SCHEMA_DESCRIPTION
    return f"{schema} | {nl_query}"
